default: cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/MortgageApp.java
	javac cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/MortgageApp.java

run: cpsc2150/mortgages/MortgageApp.class
	java cpsc2150.mortgages.MortgageApp

clean:
	rm -f *.class
