default: cpsc2150/labs/lab2/Customer.java cpsc2150/labs/lab2/Mortgage.java cpsc2150/labs/lab2/MortgageApp.java
	javac cpsc2150/labs/lab2/Customer.java cpsc2150/labs/lab2/Mortgage.java cpsc2150/labs/lab2/MortgageApp.java 

run: cpsc2150/labs/lab2/MortgageApp.class
	java cpsc2150/labs/lab2.MortgageApp


clean:
	rm -f *.class
