default: src/cpsc2150/Speedster/DirectionalSpeedster.java src/cpsc2150/Speedster/IDirectionalSpeedster.java
	javac src/cpsc2150/Speedster/DirectionalSpeedster.java src/cpsc2150/Speedster/IDirectionalSpeedster.java

/*test: src/cpsc2150/Speedster/DirectionalSpeedster.java src/cpsc2150/Speedster/IDirectionalSpeedster.java test/cpsc2150/Speedster/DirectionalSpeedsterTest.java
	javac -cp .:/usr/share/java/junit4.jar src/cpsc2150/Speedster/DirectionalSpeedster.java src/cpsc2150/Speedster/IDirectionalSpeedster.java test/cpsc2150/Speedster/DirectionalSpeedsterTest.java*/

test: src/cpsc2150/Speedster/DirectionalSpeedster.class src/cpsc2150/Speedster/IDirectionalSpeedster.class test/cpsc2150/Speedster/DirectionalSpeedsterTest.class
	java -cp .:/usr/share/java/junit4.jar org.junit.runner.JUnitCore cpsc2150.Speedster.DirectionalSpeedsterTest

