default: cpsc2150/MyQueue/ArrayQueueImp.java cpsc2150/MyQueue/ListQueueImp.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/IntegerQueueApp.java cpsc2150/MyQueue/StringQueueApp.java
	javac cpsc2150/MyQueue/ArrayQueueImp.java cpsc2150/MyQueue/ListQueueImp.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/IntegerQueueApp.java cpsc2150/MyQueue/StringQueueApp.java

runInt: cpsc2150/MyQueue/IntegerQueueApp.class
	java cpsc2150/MyQueue.IntegerQueueApp

runString: cpsc2150/MyQueue/StringQueueApp.class
	java cpsc2150/MyQueue.StringQueueApp

clean:
	rm -f *.class
